; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
build_flags = 
	-D ESP_NOW_RECEIVER

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
build_flags = 
	-D USING_NODEMCU_V2
	-D ESPNOW_RECEIVER
build_src_filter = +<*> -<main.cpp> -<esp32s3_esp-now_receiver.cpp>

[env:esp32-s3-zero]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_upload.flash_size = 4MB
board_build.psram_type = qio
board_build.partitions = default.csv
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DBOARD_HAS_PSRAM
	-D USING_ESP32_S3_ZERO
	-D ESPNOW_SENDER
build_src_filter = +<*> -<esp8266_esp-now_receiver.cpp> -<esp32s3_esp-now_receiver.cpp>

[env:cardputer]
board = esp32-s3-devkitc-1
platform = espressif32
framework = arduino
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
upload_speed = 1500000
monitor_speed = 115200
build_src_filter = +<*> -<esp8266_esp-now_receiver.cpp> -<main.cpp>